[package]
name = "danake-rs"
version = "0.1.0"
authors = ["Neal Lester <neal@3dsafety.com>"]

[dependencies]
uuid = "0.7"

#Serde

#serde = "1.0"
#serde_derive = "1.0"
#serde_json = "1.0"

#erased-serde = "0.3"

